# Generated by Django 6.1.1 on 2026-09-08 21:35

import apps.jobs.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('language', models.CharField(choices=[('auto', 'Igual que la oferta'), ('es', 'Español'), ('en', 'Inglés')], default='auto', max_length=4)),
                ('include_summary', models.BooleanField(default=False)),
                ('cv_source_text', models.TextField(blank=True)),
                ('cv_upload', models.FileField(blank=True, null=True, upload_to=apps.jobs.models.upload_path)),
                ('cv_text', models.TextField(blank=True)),
                ('cv_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('extraction_method', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'En cola'), ('PARSING', 'Leyendo el CV'), ('TAILORING', 'Adaptando a la oferta'), ('RENDERING', 'Compilando el PDF'), ('DONE', 'Listo'), ('FAILED', 'Falló'), ('QUOTA_EXHAUSTED', 'Sin cupo diario')], default='PENDING', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('parsed_cv', models.JSONField(blank=True, default=dict)),
                ('tailor_patch', models.JSONField(blank=True, default=dict)),
                ('final_cv', models.JSONField(blank=True, default=dict)),
                ('match_report', models.JSONField(blank=True, default=dict)),
                ('linkedin_pack', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('models_used', models.JSONField(blank=True, default=list)),
                ('pages', models.PositiveSmallIntegerField(default=0)),
                ('trimmed_bullets', models.PositiveSmallIntegerField(default=0)),
                ('ats_missing', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tex', 'Fuente LaTeX'), ('pdf', 'PDF'), ('json', 'Datos JSON'), ('zip', 'Paquete completo')], max_length=8)),
                ('file', models.FileField(upload_to=apps.jobs.models.artifact_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='jobs.job')),
            ],
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', '-created_at'], name='jobs_job_user_id_58dc09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='artifact',
            unique_together={('job', 'kind')},
        ),
    ]
