# Generated by Django 6.1.1 on 2026-09-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='kind',
            field=models.CharField(choices=[('tex', 'Fuente LaTeX'), ('pdf', 'PDF'), ('json', 'Datos JSON'), ('zip', 'Paquete completo'), ('png', 'Vista previa')], max_length=8),
        ),
    ]
