# Generated by Django 6.1.1 on 2026-09-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CvParse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('data', models.JSONField()),
                ('model_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LlmCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('purpose', models.CharField(choices=[('parse', 'Parse del CV'), ('tailor', 'Adaptación a la oferta'), ('repair', 'Reparación de JSON')], max_length=16)),
                ('prompt_version', models.CharField(max_length=16)),
                ('model_id', models.CharField(max_length=200)),
                ('data', models.JSONField(default=dict)),
                ('raw_response', models.TextField(blank=True)),
                ('finish_reason', models.CharField(blank=True, max_length=32)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
