# Generated by Django 6.1.1 on 2026-09-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcall',
            name='cost_usd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='llmcall',
            name='provider',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
